version: "3.9"

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: approval_user
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: approval_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mock:
    build:
      context: .
      dockerfile: apps/mock/Dockerfile
    environment:
      NODE_ENV: development
      APP_PORT: 4001
    ports:
      - "4001:4001"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      NODE_ENV: development
      APP_PORT: 3000
      DATABASE_URL: postgres://approval_user:example_password@db:5432/approval_db
      MASTERDATA_BASE_URL: http://mock:4001
      METRIC_BASE_URL: http://mock:4001
      NOTIFICATION_BASE_URL: http://mock:4001
    ports:
      - "3000:3000"
    depends_on:
      - db
      - mock

volumes:
  db_data:
